# Generated by Django 4.1.5 on 2023-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='character',
            field=models.ManyToManyField(related_name='char_to_ep', to='main.character'),
        ),
    ]
